bot_token: "YOUR_BOT_TOKEN"  # 会被环境变量覆盖
channel_id: "@your_channel"
admin_id: 123456789  # 你的Telegram用户ID
support_link: "https://t.me/your_support"
private_channel_link: "https://t.me/your_private_channel"
app_link: "https://t.me/your_app"

schedule:
  daily_message:
    time: "09:00"  # UTC时间
    message: "早安！这是今天的每日更新。"
